<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/ConfigurationSaveQueue.cs" Link="ConfigurationSaveQueue.cs" />
    <Compile Include="../../src/Configuration.cs" Link="Configuration.cs" />
    <Compile Include="../../src/PerformanceDiagnostics.cs" Link="PerformanceDiagnostics.cs" />
    <Compile Include="../../src/CharacterIndexRetention.cs" Link="CharacterIndexRetention.cs" />
    <Compile Include="../../src/SyncProvider.cs" Link="SyncProvider.cs" />
  </ItemGroup>
</Project>
